[package]
name = "day7"
version = "0.1.0"
authors = ["Enoch Chau <enoch965@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
